name: publish template to nuget

on: [push]

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true

jobs:
  publish:
    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: [ '6.0.x' ]

    steps:
      - uses: actions/checkout@v3
      - name: show base path
        run: echo ${{ github.workspace }} 
             
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release nuget.csproj

      - name: publish
        run: dotnet pack --configuration Release  nuget.csproj

      - name: Publish the package to Nuget
        run: dotnet nuget push ${{ github.workspace }}\nirojlib.*.nupkg --api-key ${{secrets.NUGET_TOKEN}} --source ${{secrets.NUGET_URL}}  
     

      